products = [
    {
      '_id': '1',
      'name': 'Mobile Legends Bang Bang',
      'image': '/images/MLBB.jpg',
      'description':
        'Buy Mobile Legends Diamonds, Twilight Pass and Weekly Diamond Pass in seconds! TheLootStop offers easy, safe and convenient ML top ups.',
      'brand': 'Methamphetamine',
      'category': 'Electronics',
      'price': 89.99,
      'countInStock': 0,
      'rating': 5.0,
      'numReviews': 12,
      'unit': 'Diamonds',
      'unitDesign': {'emoji': '💎', 'color': '#28a745', 'borderColor': '#1e7e34'},
    },
    {
      '_id': '2',
      'name': 'Call of Duty Mobile',
      'image': '/images/CODM.jpg',
      'description':
        'Buy Garena Shells for Call of Duty Mobile CP in seconds! TheLootStop offers easy, safe and convenient Call of Duty Mobile top ups.',
      'brand': 'Apple',
      'category': 'Electronics',
      'price': 599.99,
      'countInStock': 7,
      'rating': 4.0,
      'numReviews': 8,
      'unit': 'Shells',
      'unitDesign': { 'image': '/images/Item_Shells.png', 'color': '#fd7e14', 'borderColor': '#d35400'},
    },
    {
      '_id': '3',
      'name': 'Leauge of Legends: Wild Rift',
      'image': '/images/LOL.png',
      'description':
        'Buy Wild Cores for League of Legends: Wild Rift (Mobile). TheLootStop offers easy, safe and convenient Wild Rift Top ups.',
      'brand': 'Cannon',
      'category': 'Electronics',
      'price': 929.99,
      'countInStock': 5,
      'rating': 3.5,
      'numReviews': 12,
      'unit': 'Wild Cores',
      'unitDesign': { 'image': '/images/Item_Wildcore.png', 'color': '#0dcaf0', 'borderColor': '#0aa2c0'},
    },
    {
      '_id': '4',
      'name': 'Roblox',
      'image': '/images/Roblox.png',
      'description':
        'Buy Roblox Digital Gift Card and enjoy a hassle-free top-up experience only at TheLootStop. TheLootStop offers easy, safe and convenient Roblox top ups.',
      'brand': 'Sony',
      'category': 'Electronics',
      'price': 399.99,
      'countInStock': 11,
      'rating': 5,
      'numReviews': 12,
      'unit': 'Robux',
      'unitDesign': { 'image': '/images/Item_Robux.png', 'color': '#6f42c1', 'borderColor': '#4c0099'},
    },
    {
      '_id': '5',
      'name': 'Genshin Impact',
      'image': '/images/Genshin.jpg',
      'description':
        'Buy Genshin Impact Primogems and enjoy a hassle-free top-up experience at TheLootStop. TheLootStop offers easy, safe and convenient Genshin Impact top ups.',
      'brand': 'Logitech',
      'category': 'Electronics',
      'price': 49.99,
      'countInStock': 7,
      'rating': 3.5,
      'numReviews': 10,
      'unit': 'Primogems',
      'unitDesign': { 'image': '/images/Item_Primogem.webp', 'color': '#dc3545', 'borderColor': '#a71d2a'},
    },
    {
      '_id': '6',
      'name': 'Honkai: Star Rail',
      'image': '/images/Honkai.jpg',
      'description':
        'Buy Honkai: Star Rail Oneiric Shards and enjoy a hassle-free top-up experience at TheLootStop. TheLootStop offers easy, safe and convenient Honkai: Star Rail top ups.',
      'brand': 'Amazon',
      'category': 'Electronics',
      'price': 29.99,
      'countInStock': 0,
      'rating': 4,
      'numReviews': 12,
      'unit': 'Oneiric Shards',
      'unitDesign': { 'image': '/images/Item_Oneiric_Shard.webp', 'color': '#6930c3', 'borderColor': '#4d1e99'},
    },
    {
      '_id': '7',
      'name': 'Honor of Kings',
      'image': '/images/HOK.png',
      'description':
        'Buy Honor of Kings Tokens and enjoy a hassle-free top-up experience at TheLootStop. TheLootStop offers easy, safe and convenient Honor of Kings top ups.',
      'brand': 'Amazon',
      'category': 'Electronics',
      'price': 29.99,
      'countInStock': 3,
      'rating': 5,
      'numReviews':26,
      'unit': 'Tokens',
      'unitDesign': {'emoji': '🪙', 'color': '#ffc107', 'borderColor': '#cc9900'},
    },
    {
      '_id': '8',
      'name': 'Love and Deepspace',
      'image': '/images/LID.jpg',
      'description':
        'Buy Love and Deepspace Crystals and enjoy a hassle-free top-up experience at TheLootStop. TheLootStop offers easy, safe and convenient Love and Deepspace top ups.',
      'brand': 'Amazon',
      'category': 'Electronics',
      'price': 29.99,
      'countInStock': 3,
      'rating': 4.5,
      'numReviews': 7,
      'unit': 'Crystals',
      'unitDesign': {'emoji': '💎', 'color': '#e91e63', 'borderColor': '#ad1457'},
    },
  ]
  
  
